const app=document.querySelector('#app'),status=document.querySelector('#status'),toastEl=document.querySelector('#toast');
const SUPABASE_URL='https://npnkvwcghmkwddqumbkk.supabase.co';
const SUPABASE_KEY='sb_publishable_m4CfqNIdEEgjmBas08XGHQ_N1_Gjlhb';
let sb=null,session=null,currentProfile=null,currentBranch=null,consultOnly=false,cache={products:[],inventory:[],branches:[],categories:[]};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){toastEl.textContent=msg;toastEl.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toastEl.classList.add('hidden'),2800)}
function setStatus(text,on=true){status.textContent=(on?'🟢 ':'🔴 ')+text;status.classList.toggle('off',!on)}
function money(v){return '$'+Number(v||0).toFixed(2)}
function price(v){if(v==null||v==='')return 'Consultar';return money(v)}
function branchName(){return currentBranch?.nombre||currentBranch?.name||'Seleccionar sucursal'}
function branchAddress(){return currentBranch?.direccion||currentBranch?.dirección||currentBranch?.address||currentBranch?.['Dirección']||'Dirección no configurada'}
function productId(p){return p?.id??p?.identificación??p?.identificacion??p?.producto_id??p?.['ID del producto']}
function productName(p){return p?.nombre??p?.name??'Producto'}
function productImage(p){return p?.imagen_url??p?.image_url??p?.['URL de la imagen']??''}
function productPrice(p){return Number(p?.precio_base??p?.precio??p?.price??0)}
function productCost(p){return Number(p?.costo_base??p?.costo??p?.cost??0)}
function profileRole(){return String(currentProfile?.rol||'').toLowerCase()}
function canSwitchBranch(){return profileRole()==='admin'||profileRole()==='administrador'}
function saleDate(s){return s?.sale_date??s?.fecha??s?.created_at??new Date().toISOString()}
function salePayment(s){return s?.payment_method??s?.metodo_pago??''}
function invProductId(i){return i?.producto_id??i?.['ID del producto']??i?.['ID del produc']}
function invStock(i){return Number(i?.cantidad??i?.stock??i?.existencias??i?.['cantidad disponible']??i?.['Cantidad']??0)}
function profileBranchId(){if(!currentProfile)return null;return currentProfile.sucursal_id||currentProfile.sucursalId||currentProfile['ID de sucursal']||currentProfile['ID de sucursa']||null}
function activeNav(key){document.querySelectorAll('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===key))}
function ensureNav(active='home'){
  if(!session){document.getElementById('bottomNav')?.remove();return}
  let nav=document.getElementById('bottomNav');
  if(!nav){nav=document.createElement('nav');nav.id='bottomNav';nav.className='bottom';document.body.appendChild(nav)}
  nav.innerHTML=`<button data-nav="home" onclick="dashboard()">⌂<span>Inicio</span></button><button data-nav="products" onclick="productos()">▦<span>Productos</span></button><button data-nav="sell" onclick="ventas()">＋<span>Vender</span></button><button data-nav="expenses" onclick="gastos()">−<span>Gastos</span></button><button data-nav="reports" onclick="reportes()">⌁<span>Reportes</span></button>`;
  activeNav(active)
}
function showPage(html,nav='home'){app.innerHTML=html;ensureNav(nav);window.scrollTo({top:0,behavior:'instant'})}
async function init(){
  if(!navigator.onLine)setStatus('Sin conexión',false);
  try{
    if(!window.supabase)throw new Error('No se pudo cargar la librería de Supabase.');
    sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
    const r=await sb.auth.getSession(); if(r.error)throw r.error; session=r.data.session;
    sb.auth.onAuthStateChange((_e,s)=>{session=s;if(s)loadApp();else login()}); setStatus('Listo',true);
  }catch(e){console.error(e);setStatus(navigator.onLine?'Sincronización pendiente':'Sin conexión',navigator.onLine)}
  if(session)await loadApp();else login();
}
function login(){document.getElementById('bottomNav')?.remove();app.innerHTML=`<section class="login card"><img src="logo.png" alt="BIOVITAL"><h1>Bienvenido a BIOVITAL</h1><p class="muted">Ventas, inventario y reportes en un solo lugar.</p><div class="field"><label>Correo electrónico</label><input id="email" type="email" autocomplete="username" placeholder="correo@biovital.com"></div><div class="field"><label>Contraseña</label><input id="pass" type="password" autocomplete="current-password" placeholder="••••••••"></div><button class="btn primary" onclick="signIn()">Ingresar</button><p class="hint">El acceso administrativo usa la autenticación segura de Supabase.</p></section>`;setStatus('Listo',navigator.onLine)}
async function signIn(){if(!navigator.onLine)return toast('Necesitas conexión para iniciar sesión.');const email=$('email')?.value.trim(),password=$('pass')?.value;if(!email||!password)return toast('Escribe tu correo y contraseña.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return toast(error.message);session=data.session;await loadApp()}
async function signOut(){await sb.auth.signOut();session=null;currentProfile=null;currentBranch=null;login()}
async function loadApp(){setStatus('Conectado');await loadProfile();await loadBranches();dashboard()}
async function loadProfile(){currentProfile=null;if(!session)return;try{const {data}=await sb.from('perfiles').select('*').eq('id',session.user.id).maybeSingle();currentProfile=data||{id:session.user.id,email:session.user.email}}catch(e){currentProfile={id:session.user.id,email:session.user.email}}}
async function loadBranches(){if(!sb)return;const {data,error}=await sb.from('sucursales').select('*').order('nombre');if(!error)cache.branches=data||[];const pid=profileBranchId();currentBranch=cache.branches.find(b=>String(b.id)===String(pid))||currentBranch||cache.branches[0]||null}
async function getProducts(){const {data,error}=await sb.from('productos').select('*').order('nombre');if(error){toast('No se pudieron cargar productos: '+error.message);return cache.products}cache.products=data||[];return cache.products}
async function getCategories(){if(cache.categories.length)return cache.categories;let r=await sb.from('categorías').select('*').order('nombre');if(r.error)r=await sb.from('categorias').select('*').order('nombre');if(!r.error)cache.categories=r.data||[];return cache.categories}
function categoryId(c){return c?.id??c?.identificacion??c?.identificación}
function categoryName(c){return c?.nombre??c?.name??c?.descripcion??c?.descripción??'Categoría'}
async function getInventory(){if(!currentBranch)return [];let {data,error}=await sb.from('inventario').select('*').eq('sucursal_id',currentBranch.id);if(error){const r=await sb.from('inventario').select('*').eq('ID de sucursa',currentBranch.id);data=r.data;error=r.error}if(error){toast('No se pudo cargar el inventario');return cache.inventory}cache.inventory=data||[];return cache.inventory}
async function dashboard(){
 if(!session)return login();const inv=await getInventory();const low=inv.filter(i=>invStock(i)<=5).length;const start=new Date();start.setHours(0,0,0,0);let salesToday=0,gainToday=0;
 try{const {data:v,error}=await sb.from('ventas').select('*').eq('branch_id',currentBranch?.id).gte('sale_date',start.toISOString());if(!error){salesToday=(v||[]).reduce((s,x)=>s+Number(x.total||0),0);gainToday=(v||[]).reduce((s,x)=>s+Number(x.total||0)-Number(x.subtotal||0)+0,0)}}catch(e){}
 showPage(`<section class="hero"><div><span class="eyebrow">Hola, vamos al grano</span><h1>Resumen de hoy</h1><p class="muted">${esc(branchName())} · ${consultOnly?'Modo consulta':'Modo normal'}</p>${canSwitchBranch()?'<button class="smallbtn" onclick="switchBranch()">🏪 Cambiar sucursal</button>':''}</div><div class="date">${new Date().toLocaleDateString('es-EC',{day:'2-digit',month:'short'}).replace('.','')}</div></section>
 <section class="salesCard"><div><span>VENTAS DE HOY</span><strong>${money(salesToday)}</strong><small>${salesToday?'Ventas registradas':'0 ventas registradas'}</small></div><span class="pill">● AL DÍA</span></section>
 <div class="stats"><button onclick="reportes()"><span>● Ventas hoy</span><b>${money(salesToday)}</b><small>Ver reportes →</small></button><button onclick="gastos()"><span>● Gastos</span><b class="orange">Consultar</b><small>Ver gastos →</small></button></div>
 <h2>Acciones rápidas</h2><div class="quick"><button onclick="ventas()">＋ Nueva venta</button><button class="soft" onclick="gastos(true)">− Nuevo gasto</button></div>
 <section class="card section"><div class="row"><div><h2>Inventario</h2><p class="muted">${esc(branchName())}</p></div><button class="smallbtn" onclick="inventory()">Ver inventario</button></div><div class="empty">${low?`⚠️ ${low} productos con stock bajo o agotado.`:'Inventario sin alertas críticas.'}</div></section>
 <section class="card section"><div class="row"><div><h2>Facturas y pedidos</h2><p class="muted">Genera comprobantes después de cada venta.</p></div><button class="smallbtn" onclick="ventas()">Nueva venta</button></div><div class="empty">Cada venta puede convertirse en PDF y compartirse.</div></section>`, 'home')
}
async function inventory(){if(!session)return login();const [products,inv]=await Promise.all([getProducts(),getInventory()]);const map={};products.forEach(p=>map[String(productId(p))]=p);showPage(`<section class="card"><div class="row"><div><h1>Inventario</h1><p class="muted">${esc(branchName())}</p></div><button class="smallbtn" onclick="dashboard()">← Inicio</button></div><div class="search"><input id="invSearch" placeholder="🔎 Buscar producto..." oninput="renderInventory()"></div><div id="invList" class="list"></div></section>`,'products');window.__invMap=map;window.__invData=inv;renderInventory()}
function renderInventory(){const list=$('invList');if(!list)return;const q=($('invSearch')?.value||'').toLowerCase();const rows=(window.__invData||[]).filter(i=>{const p=window.__invMap?.[String(invProductId(i))];return `${productName(p)} ${invProductId(i)}`.toLowerCase().includes(q)});list.innerHTML=rows.length?rows.map(i=>{const p=window.__invMap[String(invProductId(i))]||{};const st=invStock(i);return `<div class="listrow"><div><b>${esc(productName(p))}</b><small>ID: ${esc(invProductId(i))}</small></div><div class="stock ${st<=0?'danger':st<=5?'warn':''}">${st} unid.</div></div>`}).join(''):`<div class="empty">No hay registros de inventario para esta sucursal.</div>`}
async function productos(){const ps=await getProducts();showPage(`<section class="card"><div class="row"><div><h1>Productos</h1><p class="muted">Catálogo, precios, costos y alta de productos.</p></div><button class="smallbtn" onclick="newProduct()">＋ Nuevo</button></div><div class="search"><input id="pSearch" placeholder="🔎 Buscar producto..." oninput="renderProducts()"></div><div id="pList" class="catalog"></div></section>`,'products');window.__products=ps;renderProducts()}
function renderProducts(){const el=$('pList');if(!el)return;const q=($('pSearch')?.value||'').toLowerCase();const ps=(window.__products||[]).filter(p=>`${productName(p)} ${p.codigo||''}`.toLowerCase().includes(q));el.innerHTML=ps.map(p=>`<article class="product"><div class="productImg">${productImage(p)?`<img src="${esc(productImage(p))}" alt="${esc(productName(p))}">`:'🌿'}</div><h3>${esc(productName(p))}</h3><p>${esc(p.descripcion||'')}</p><strong>${price(productPrice(p))}</strong><small>Costo: ${money(productCost(p))}</small><button class="smallbtn full" onclick="editProduct('${esc(productId(p))}')">Editar</button></article>`).join('')||'<div class="empty">No hay productos. Puedes crear el primero con “＋ Nuevo”.</div>'}
async function newProduct(){const cats=await getCategories();showPage(`<section class="card formcard"><div class="row"><h1>Nuevo producto</h1><button class="smallbtn" onclick="productos()">←</button></div><div class="field"><label>Nombre</label><input id="npName" placeholder="Nombre del producto"></div><div class="field"><label>Categoría</label><select id="npCat"><option value="">Sin categoría</option>${cats.map(c=>`<option value="${esc(categoryId(c))}">${esc(categoryName(c))}</option>`).join('')}</select></div><div class="twocol"><div class="field"><label>Precio de venta</label><input id="npPrice" type="number" step="0.01" min="0" placeholder="0.00"></div><div class="field"><label>Costo</label><input id="npCost" type="number" step="0.01" min="0" placeholder="0.00"></div></div><div class="field"><label>Stock inicial en ${esc(branchName())}</label><input id="npStock" type="number" step="0.01" min="0" value="0"></div><div class="field"><label>Descripción</label><textarea id="npDesc" rows="3" placeholder="Descripción"></textarea></div><div class="field"><label>Foto del producto</label><div class="twocol"><button type="button" class="btn secondary" onclick="document.getElementById('npGallery').click()">🖼️ Galería</button><button type="button" class="btn secondary" onclick="document.getElementById('npCamera').click()">📷 Cámara</button></div><input id="npGallery" type="file" accept="image/*" hidden onchange="previewProductImage(this)"><input id="npCamera" type="file" accept="image/*" capture="environment" hidden onchange="previewProductImage(this)"><div id="npPreview" class="productImg" style="margin-top:10px">🌿</div></div><button class="btn primary" onclick="saveProduct()">Guardar producto</button></section>`,'products')}
function previewProductImage(input){const file=input.files?.[0];if(!file)return;window.__productImageFile=file;const r=new FileReader();r.onload=()=>{const el=$('npPreview');if(el)el.innerHTML=`<img src="${r.result}" alt="Vista previa">`};r.readAsDataURL(file)}
async function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Matho(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',0.72))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function saveProduct(){if(consultOnly)return toast('Modo consulta: no se pueden registrar cambios.');const nombre=$('npName')?.value.trim(),categoria_id=$('npCat')?.value||null,precio=Number($('npPrice')?.value||0),costo=Number($('npCost')?.value||0),stock=Number($('npStock')?.value||0),descripcion=$('npDesc')?.value.trim();if(!nombre||precio<0||costo<0||stock<0)return toast('Completa los datos del producto.');const payload={nombre,categoria_id,precio_base:precio,costo_base:costo,descripcion,activo:true};const {data,error}=await sb.from('productos').insert(payload).select('*').single();if(error)return toast('No se pudo guardar el producto: '+error.message);if(window.__productImageFile){const img=await compressImage(window.__productImageFile);const ir=await sb.from('productos').update({imagen_url:img}).eq('id',data.id);if(ir.error)toast('Producto creado. Para guardar fotos falta agregar la columna imagen_url en Supabase.');}if(currentBranch){const inv={sucursal_id:currentBranch.id,producto_id:data.id,cantidad:stock,precio_venta:precio,costo:costo,stock_minimo:3};const {error:ie}=await sb.from('inventario').upsert(inv,{onConflict:'sucursal_id,producto_id'});if(ie)toast('Producto creado, pero no se pudo crear su inventario: '+ie.message)}toast('✅ Producto creado.');window.__productImageFile=null;productos()}
async function editProduct(id){const p=(cache.products||[]).find(x=>String(productId(x))===String(id))||window.__products?.find(x=>String(productId(x))===String(id));if(!p)return toast('Producto no encontrado.');const cats=await getCategories();let inv=null;if(currentBranch){const r=await sb.from('inventario').select('*').eq('sucursal_id',currentBranch.id).eq('producto_id',id).maybeSingle();if(!r.error)inv=r.data||null}const stock=Number(inv?.cantidad??0),stockMin=Math.max(3,Number(inv?.stock_minimo??3));showPage(`<section class="card formcard"><div class="row"><h1>Editar producto</h1><button class="smallbtn" onclick="productos()">←</button></div><div class="field"><label>Nombre</label><input id="epName" value="${esc(productName(p))}"></div><div class="field"><label>Categoría</label><select id="epCat"><option value="">Sin categoría</option>${cats.map(c=>`<option value="${esc(categoryId(c))}" ${String(categoryId(c))===String(p.categoria_id||'')?'selected':''}>${esc(categoryName(c))}</option>`).join('')}</select></div><div class="twocol"><div class="field"><label>Precio de venta</label><input id="epPrice" type="number" step="0.01" min="0" value="${esc(productPrice(p))}"></div><div class="field"><label>Costo</label><input id="epCost" type="number" step="0.01" min="0" value="${esc(productCost(p))}"></div></div><div class="twocol"><div class="field"><label>Stock actual</label><input id="epStock" type="number" step="0.01" min="0" value="${stock}"></div><div class="field"><label>Stock mínimo</label><input id="epStockMin" type="number" step="0.01" min="3" value="${stockMin}"></div></div><div class="field"><label>Descripción</label><textarea id="epDesc" rows="3">${esc(p.descripcion||'')}</textarea></div><div class="field"><label>Foto</label><div class="twocol"><button type="button" class="btn secondary" onclick="document.getElementById('epGallery').click()">🖼️ Galería</button><button type="button" class="btn secondary" onclick="document.getElementById('epCamera').click()">📷 Cámara</button></div><input id="epGallery" type="file" accept="image/*" hidden onchange="previewEditImage(this)"><input id="epCamera" type="file" accept="image/*" capture="environment" hidden onchange="previewEditImage(this)"><div id="epPreview" class="productImg" style="margin-top:10px">${productImage(p)?`<img src="${esc(productImage(p))}" alt="Foto actual">`:'🌿'}</div></div><button class="btn primary" onclick="updateProduct('${esc(id)}')">Guardar cambios</button></section>`,'products')}
function previewEditImage(input){const file=input.files?.[0];if(!file)return;window.__editProductImageFile=file;const r=new FileReader();r.onload=()=>{const el=$('epPreview');if(el)el.innerHTML=`<img src="${r.result}" alt="Vista previa">`};r.readAsDataURL(file)}
async function updateProduct(id){if(consultOnly)return toast('Modo consulta: no se pueden registrar cambios.');const nombre=$('epName')?.value.trim(),precio=Number($('epPrice')?.value||0),costo=Number($('epCost')?.value||0),stock=Number($('epStock')?.value||0),stockMin=Number($('epStockMin')?.value||0),categoria_id=$('epCat')?.value||null,descripcion=$('epDesc')?.value.trim();if(!nombre||precio<0||costo<0||stock<0||stockMin<3)return toast('El stock mínimo debe ser 3 o mayor.');const {error}=await sb.from('productos').update({nombre,precio_base:precio,costo_base:costo,categoria_id,descripcion}).eq('id',id);if(error)return toast('No se pudo actualizar: '+error.message);if(window.__editProductImageFile){const img=await compressImage(window.__editProductImageFile);const ir=await sb.from('productos').update({imagen_url:img}).eq('id',id);if(ir.error)toast('Datos actualizados. Para guardar fotos falta agregar la columna imagen_url en Supabase.')}if(currentBranch){const {error:ie}=await sb.from('inventario').update({cantidad:stock,precio_venta:precio,costo:costo,stock_minimo:stockMin}).eq('sucursal_id',currentBranch.id).eq('producto_id',id);if(ie)return toast('Producto actualizado, pero no se pudo guardar el inventario: '+ie.message)}toast('✅ Producto e inventario actualizados.');window.__editProductImageFile=null;productos()}
async function ventas(){if(!session)return login();const ps=await getProducts();const inv=await getInventory();const byId={};inv.forEach(i=>byId[String(invProductId(i))]=i);showPage(`<section class="card formcard"><div class="row"><div><h1>Nueva venta</h1><p class="muted">${esc(branchName())}</p></div><button class="smallbtn" onclick="dashboard()">←</button></div>${ps.length?`<div class="field"><label>Producto</label><select id="saleProduct" onchange="fillSalePrice()">${ps.map(p=>{const i=byId[String(productId(p))];return `<option value="${esc(productId(p))}">${esc(productName(p))} — ${price(i?.precio_venta??productPrice(p))} · Stock ${invStock(i||{})}</option>`}).join('')}</select></div><div class="twocol"><div class="field"><label>Cantidad</label><input id="saleQty" type="number" min="1" value="1" oninput="fillSalePrice()"></div><div class="field"><label>Total</label><input id="saleTotal" type="number" step="0.01" placeholder="0.00"></div></div><div class="field"><label>Cliente (opcional)</label><input id="saleClient" placeholder="Nombre del cliente"></div><div class="field"><label>Correo del cliente (opcional)</label><input id="saleEmail" type="email" placeholder="cliente@correo.com"></div><div class="field"><label>Método de pago</label><select id="salePay"><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="otro">Otro</option></select></div><button class="btn primary" onclick="saveSale()" ${consultOnly?'disabled':''}>Registrar venta</button>`:'<div class="empty">No hay productos registrados. Primero crea un producto.</div><button class="btn secondary" onclick="newProduct()">＋ Crear producto</button>'}</section>`,'sell');window.__saleInventory=byId;fillSalePrice()}
function fillSalePrice(){const ps=window.__products||cache.products;const p=ps.find(x=>String(productId(x))===String($('saleProduct')?.value));if(!p)return;const inv=window.__saleInventory?.[String(productId(p))];const unit=Number(inv?.precio_venta??productPrice(p));const qty=Number($('saleQty')?.value||1);if($('saleTotal'))$('saleTotal').value=(unit*qty).toFixed(2)}
function invoiceData(sale,detail,product){const saved=JSON.parse(localStorage.getItem(invoiceKey(sale.id))||'null')||{};return {order:saved.order||orderNumber(sale.id),client:saved.client??'',email:saved.email??'',address:saved.address??branchAddress(),branch:saved.branch??branchName(),notes:saved.notes??'',sale,detail,product}}
async function saveSale(){
 if(consultOnly)return toast('Modo consulta: no se pueden registrar cambios.');const producto_id=$('saleProduct')?.value,cantidad=Number($('saleQty')?.value||0),total=Number($('saleTotal')?.value||0),payment_method=$('salePay')?.value||'efectivo';
 if(!currentBranch)return toast('Selecciona una sucursal.');if(!producto_id||cantidad<=0||total<=0)return toast('Completa producto, cantidad y total.');
 const {data:inv,error:ie}=await sb.from('inventario').select('*').eq('sucursal_id',currentBranch.id).eq('producto_id',producto_id).maybeSingle();if(ie)return toast('No se pudo consultar el inventario: '+ie.message);if(!inv)return toast('Este producto no tiene inventario en esta sucursal.');const stock=invStock(inv);if(stock<cantidad)return toast(`Stock insuficiente. Disponible: ${stock}`);
 const product=(await getProducts()).find(p=>String(productId(p))===String(producto_id));const costo=Number(inv.costo??productCost(product));const subtotal=total;const notes=[$('saleClient')?.value.trim(),$('saleEmail')?.value.trim()].filter(Boolean).join(' · ');
 const payload={sucursal_id:currentBranch.id,seller_id:session.user.id,sale_date:new Date().toISOString(),metodo_pago,subtotal, descuento:0,total,observacion:notes||null};const {data:venta,error:ve}=await sb.from('ventas').insert(payload).select('*').single();if(ve)return toast('No se pudo registrar la venta: '+ve.message);
 const {data:det,error:de}=await sb.from('venta_detalles').insert({venta_id:venta.id,producto_id,cantidad,precio_unitario:total/cantidad,costo_unitario:costo,subtotal}).select('*').single();if(de){await sb.from('ventas').delete().eq('id',venta.id);return toast('No se pudo guardar el detalle de la venta: '+de.message)}
 const {error:ue}=await sb.from('inventario').update({cantidad:stock-cantidad}).eq('id',inv.id);if(ue){await sb.from('venta_detalles').delete().eq('id',det.id);await sb.from('ventas').delete().eq('id',venta.id);return toast('No se pudo actualizar el stock: '+ue.message)}
 localStorage.setItem(invoiceKey(venta.id),JSON.stringify({order:orderNumber(venta.id),client:$('saleClient')?.value.trim()||'',email:$('saleEmail')?.value.trim()||'',address:branchAddress(),branch:branchName(),notes:''}));toast('✅ Venta registrada y stock actualizado.');showInvoice(venta,det,product)}
function invoiceHTML(data,editable=false){const s=data.sale,d=data.detail,p=data.product||{};return `<div class="invoice" id="invoiceDoc"><div class="invoiceHead"><img src="logo.png" alt="BIOVITAL"><div><h2>BIOVITAL</h2><small>Fuerza Natural</small></div><div class="invoiceMeta"><b>PEDIDO</b><strong>${esc(data.order)}</strong><small>${new Date(saleDate(s)).toLocaleString('es-EC')}</small></div></div><div class="invoiceGrid"><div><b>Sucursal</b><span>${esc(data.branch)}</span></div><div><b>Dirección</b><span>${esc(data.address)}</span></div><div><b>Cliente</b><span>${esc(data.client||'Consumidor final')}</span></div><div><b>Pago</b><span>${esc(salePayment(s)||'')}</span></div></div><table><thead><tr><th>Producto</th><th>Cant.</th><th>P. unit.</th><th>Subtotal</th></tr></thead><tbody><tr><td>${esc(productName(p))}</td><td>${esc(d.cantidad)}</td><td>${money(d.precio_unitario)}</td><td>${money(d.subtotal)}</td></tr></tbody></table><div class="invoiceTotal"><span>TOTAL</span><b>${money(s.total)}</b></div><p class="invoiceFoot">Gracias por su compra · BIOVITAL</p></div>`}
function showInvoice(sale,detail,product){const data=invoiceData(sale,detail,product);showPage(`<section class="card invoiceCard"><div class="row"><div><h1>Comprobante de pedido</h1><p class="muted">${esc(data.order)}</p></div><button class="smallbtn" onclick="dashboard()">← Inicio</button></div>${invoiceHTML(data)}<div class="invoiceActions"><button class="btn primary" onclick="downloadInvoice()">⬇️ Generar PDF</button><button class="btn share" onclick="shareInvoice()">📲 Compartir</button><button class="btn secondary" onclick="editInvoice('${esc(sale.id)}')">✏️ Editar datos</button></div></section>`,'sell');window.__invoice={sale,detail,product,data}}
function editInvoice(id){const x=window.__invoice?.data;if(!x)return;showPage(`<section class="card formcard"><div class="row"><div><h1>Editar comprobante</h1><p class="muted">El logo BIOVITAL permanece fijo.</p></div><button class="smallbtn" onclick="showInvoice(window.__invoice.sale,window.__invoice.detail,window.__invoice.product)">←</button></div><div class="field"><label>Número de pedido</label><input id="ivOrder" value="${esc(x.order)}"></div><div class="field"><label>Sucursal</label><input id="ivBranch" value="${esc(x.branch)}"></div><div class="field"><label>Dirección</label><input id="ivAddress" value="${esc(x.address)}"></div><div class="field"><label>Cliente</label><input id="ivClient" value="${esc(x.client)}"></div><div class="field"><label>Correo</label><input id="ivEmail" type="email" value="${esc(x.email)}"></div><div class="field"><label>Observaciones</label><textarea id="ivNotes" rows="3">${esc(x.notes)}</textarea></div><button class="btn primary" onclick="saveInvoiceEdits()">Guardar comprobante</button></section>`,'sell')}
function saveInvoiceEdits(){const x=window.__invoice?.data;if(!x)return;x.order=$('ivOrder').value.trim()||x.order;x.branch=$('ivBranch').value.trim()||x.branch;x.address=$('ivAddress').value.trim()||x.address;x.client=$('ivClient').value.trim();x.email=$('ivEmail').value.trim();x.notes=$('ivNotes').value.trim();localStorage.setItem(invoiceKey(x.sale.id),JSON.stringify({order:x.order,branch:x.branch,address:x.address,client:x.client,email:x.email,notes:x.notes}));showInvoice(x.sale,x.detail,x.product);toast('✅ Comprobante actualizado.')}
function invoiceText(){const x=window.__invoice?.data;if(!x)return '';return `BIOVITAL - Pedido ${x.order}\nSucursal: ${x.branch}\nDirección: ${x.address}\nCliente: ${x.client||'Consumidor final'}\nProducto: ${productName(x.product)}\nCantidad: ${x.detail.cantidad}\nTotal: ${money(x.sale.total)}\nMétodo de pago: ${salePayment(x.sale)||''}`}
async function makePdfBlob(){if(!window.jspdf)return null;const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});const x=window.__invoice?.data;if(!x)return null;const img=document.querySelector('#invoiceDoc img');let y=18;if(img){try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);doc.addImage(c.toDataURL('image/png'),'PNG',15,12,42,25);y=44}catch(e){}}doc.setFontSize(20);doc.text('BIOVITAL',65,22);doc.setFontSize(10);doc.text('Fuerza Natural',65,29);doc.setFontSize(11);doc.text(`PEDIDO: ${x.order}`,140,20);doc.text(new Date(saleDate(x.sale)).toLocaleString('es-EC'),140,27);doc.line(15,y,195,y);y+=10;doc.setFontSize(11);doc.text(`Sucursal: ${x.branch}`,15,y);y+=7;doc.text(`Dirección: ${x.address}`,15,y);y+=7;doc.text(`Cliente: ${x.client||'Consumidor final'}`,15,y);y+=12;doc.setFontSize(12);doc.text('Producto',15,y);doc.text('Cant.',110,y);doc.text('P. unit.',135,y);doc.text('Subtotal',170,y);y+=8;doc.setFontSize(11);doc.text(productName(x.product).slice(0,48),15,y);doc.text(String(x.detail.cantidad),110,y);doc.text(money(x.detail.precio_unitario),135,y);doc.text(money(x.detail.subtotal),170,y);y+=14;doc.line(15,y,195,y);y+=10;doc.setFontSize(15);doc.text('TOTAL',140,y);doc.text(money(x.sale.total),170,y);y+=12;doc.setFontSize(10);doc.text(`Método de pago: ${salePayment(x.sale)||''}`,15,y);return doc.output('blob')}
async function downloadInvoice(){const blob=await makePdfBlob();if(!blob)return toast('No se pudo generar el PDF.');const x=window.__invoice.data;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${x.order}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('📄 PDF generado.')}
async function shareInvoice(){const blob=await makePdfBlob();const x=window.__invoice?.data;if(!x)return;const file=blob?new File([blob],`${x.order}.pdf`,{type:'application/pdf'}):null;try{if(file&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:`BIOVITAL ${x.order}`,text:invoiceText(),files:[file]});return}const url=`https://wa.me/?text=${encodeURIComponent(invoiceText())}`;window.open(url,'_blank');toast('Se abrió WhatsApp para compartir el pedido.');}catch(e){if(e.name!=='AbortError')toast('No se pudo abrir el menú de compartir.')}}
async function gastos(openForm=false){if(!session)return login();if(openForm){showPage(`<section class="card formcard"><div class="row"><h1>Nuevo gasto</h1><button class="smallbtn" onclick="dashboard()">←</button></div><div class="field"><label>Concepto</label><input id="expenseConcept" placeholder="Ej. transporte, alquiler..."></div><div class="field"><label>Categoría</label><input id="expenseCat" placeholder="Operativo"></div><div class="field"><label>Monto</label><input id="expenseAmount" type="number" step="0.01" placeholder="0.00"></div><button class="btn primary" onclick="saveExpense()">Registrar gasto</button></section>`,'expenses');return}modulePlaceholder('Gastos','Aquí verás y administrarás los gastos por día, semana, mes y año.','expenses')}
async function saveExpense(){if(consultOnly)return toast('Modo consulta: no se pueden registrar cambios.');if(!currentBranch)return toast('Selecciona una sucursal.');const concepto=$('expenseConcept')?.value.trim(),categoria=$('expenseCat')?.value.trim()||'Operativo',monto=Number($('expenseAmount')?.value||0);if(!concepto||monto<=0)return toast('Completa concepto y monto.');const {error}=await sb.from('gastos').insert({sucursal_id:currentBranch.id,usuario_id:session.user.id,concepto,categoria,monto,fecha:new Date().toISOString()});if(error)return toast('No se pudo registrar el gasto: '+error.message);toast('✅ Gasto registrado.');dashboard()}
async function reportes(){if(!session)return login();const start=new Date();start.setHours(0,0,0,0);const {data:vr,error}=await sb.from('ventas').select('*').eq('branch_id',currentBranch?.id).gte('sale_date',start.toISOString());const ventasTotal=(vr||[]).reduce((s,v)=>s+Number(v.total||0),0);showPage(`<section class="card"><div class="row"><div><h1>Reportes</h1><p class="muted">${esc(branchName())} · Hoy</p></div><button class="smallbtn" onclick="dashboard()">← Inicio</button></div><div class="stats"><div class="buttonlike"><span>● Ventas</span><b>${money(ventasTotal)}</b></div><div class="buttonlike"><span>● Gastos</span><b class="orange">Pendiente</b></div></div><div class="empty">${error?esc(error.message):'Las ventas de hoy ya se consultan por sucursal con la estructura real de Supabase.'}<br><small>El módulo de gastos se conectará después de revisar su estructura real.</small></div></section>`,'reports')}
function modulePlaceholder(title,text,nav='home'){showPage(`<section class="card"><div class="row"><div><h1>${title}</h1><p class="muted">${text}</p></div><button class="smallbtn" onclick="dashboard()">← Inicio</button></div><div class="empty">Módulo preparado para conectarse a los datos reales de Supabase.</div></section>`,nav)}
async function deudas(){if(!session)return login();modulePlaceholder('Deudas','Aquí controlarás clientes con saldo pendiente y pagos.','reports')}
function switchBranch(){if(!canSwitchBranch())return toast('Tu usuario está asignado a una sola sucursal.');if(!cache.branches.length)return toast('No hay sucursales disponibles.');showPage(`<section class="card formcard"><h1>Seleccionar sucursal</h1><p class="muted">Cada sucursal mantiene su inventario independiente.</p>${cache.branches.map(b=>`<button class="branch" onclick="chooseBranch('${esc(b.id)}')"><b>${esc(b.nombre||b.name||'Sucursal')}</b><small>${esc(b.direccion||b.dirección||'')}</small></button>`).join('')}<button class="btn secondary" onclick="dashboard()">Volver</button></section>`,'home')}
function chooseBranch(id){currentBranch=cache.branches.find(b=>String(b.id)===String(id))||currentBranch;toast('Sucursal seleccionada');dashboard()}
addEventListener('offline',()=>setStatus('Sin conexión',false));addEventListener('online',()=>{setStatus('Conectando…',true);if(sb)sb.auth.getSession().then(()=>setStatus('Listo',true)).catch(()=>setStatus('Listo',true))});init();
